//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Link()
        {
            this.LinkReports = new HashSet<LinkReport>();
            this.LinkStats = new HashSet<LinkStat>();
            this.S3Objects_Links = new HashSet<S3Objects_Links>();
            this.PackageUploadFiles = new HashSet<PackageUploadFile>();
            this.PackageUploads = new HashSet<PackageUpload>();
        }
    
        public int LinkId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string LinkUrl { get; set; }
        public System.DateTime DateFirstFound { get; set; }
        public System.DateTime DateLastFound { get; set; }
        public Nullable<System.DateTime> LinkCheckDisabledDate { get; set; }
        public string LinkCheckDisabledUser { get; set; }
        public int AttemptCount { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<System.DateTime> DateLastChecked { get; set; }
        public Nullable<int> AllTimeMinDownloadTime { get; set; }
        public Nullable<int> AllTimeMaxDownloadTime { get; set; }
        public Nullable<decimal> AllTimeStdDevDownloadTime { get; set; }
        public Nullable<int> PastWeekMinDownloadTime { get; set; }
        public Nullable<int> PastWeekMaxDownloadTime { get; set; }
        public Nullable<decimal> PastWeekStdDevDownloadTime { get; set; }
        public Nullable<System.DateTime> DateStatsUpdated { get; set; }
        public Nullable<System.DateTime> ReportNotBeforeDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkReport> LinkReports { get; set; }
        public virtual Source Source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkStat> LinkStats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S3Objects_Links> S3Objects_Links { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageUploadFile> PackageUploadFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageUpload> PackageUploads { get; set; }
    }
}
