//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkReport
    {
        public int Id { get; set; }
        public Nullable<long> ContentSize { get; set; }
        public long Mean { get; set; }
        public double StandardDeviation { get; set; }
        public int SdMaximum { get; set; }
        public int Link_LinkId { get; set; }
        public Nullable<int> LinkStatId { get; set; }
    
        public virtual Link Link { get; set; }
    }
}
