//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackageUpload()
        {
            this.PackageUploadFiles = new HashSet<PackageUploadFile>();
            this.Links = new HashSet<Link>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public string Key { get; set; }
        public Nullable<bool> PackageProcessed { get; set; }
        public string FileName { get; set; }
        public string ImsSchema { get; set; }
        public string ImsSchemaVersion { get; set; }
        public string ImsTitle { get; set; }
        public string ImsDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageUploadFile> PackageUploadFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link> Links { get; set; }
    }
}
