//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageUploadFile
    {
        public int Id { get; set; }
        public string CourseLocation { get; set; }
        public int Link_LinkId { get; set; }
        public string Protocol { get; set; }
        public string LinkName { get; set; }
        public string ParentFolder { get; set; }
        public Nullable<int> PackageUploadId { get; set; }
    
        public virtual Link Link { get; set; }
        public virtual PackageUpload PackageUpload { get; set; }
    }
}
